# Only the main branch and tags
branches:
  only:
    - dev
    - /^v\d+\.\d+\.\d+.*$/

cache:
  directories:
    - .cache

language: node_js
node_js:
  - 13

# Buildtools are going to take care of building the modpack
before_install:
  - cd ./buildtools

# Check if all necessary env. variables are set
before_script:
  - gulp travisChecks

# Build the modpack and run post-build tasks.
script:
  - . ../.travis.sh && gulp travis
  - cd ../

deploy:
  # Deploy release
  - provider: releases
    skip_cleanup: true
    token: "$GITHUB_TOKEN"
    file:
      - ./build/$SERVER_ARCHIVE.zip
      - ./build/$CLIENT_ARCHIVE.zip
      - ./build/questbook.lang
    on:
      tags: true
      condition: $TAGGED_RELEASE = true

  # Deploy release to CurseForge
  - provider: script
    edge: true
    skip_cleanup: true
    script: cd ./buildtools && npx gulp deployCurseForge && cd ../
    on:
      tags: true
      condition: $TAGGED_RELEASE = true

  # Deploy pre-release
  - provider: releases
    overwrite: true
    skip_cleanup: true
    token: "$GITHUB_TOKEN"
    tag_name: latest-dev-preview
    prerelease: true
    file:
      - ./build/$SERVER_ARCHIVE.zip
      - ./build/$CLIENT_ARCHIVE.zip
      - ./build/questbook.lang
    on:
      branch: dev
      condition: $TAGGED_RELEASE = false
